version: '3.5'

services:
  postgres-odoo-base-15-01:
    container_name: postgres_odoo-base-15-01
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /data/postgres
    volumes:
      - /home/ttdn/ttdn_k15/database_ttdn/cntt15_01_db/_data:/data/postgres
    ports:
      - "5431:5432"

   # odoo15:
  #   container_name: odoo15
  #   image: odoo:15
  #   depends_on:
  #     - postgres-odoo-base-15-01
  #   ports:
  #     - "8069:8069"
  #   volumes:
  #     - ./addons:/mnt/extra-addons
  #     - ./odoo.conf:/etc/odoo/odoo.conf
  #   environment:
  #     - HOST=postgres-odoo-base-15-01
  #     - USER=odoo
  #     - PASSWORD=odoo

